name: Desplegar en Google Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1
  SERVICE_NAME: project-pipelines-api
  REPO_NAME: roject-pipelines-repo # Nombre real del repositorio.
  DB_INSTANCE_CONNECTION_NAME: local-pointer-468022-n6:us-central1:project-pipelines-db
  DB_USER: postgres
  DB_NAME: project-pipelines

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Autenticar con Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configurar gcloud CLI
        uses: 'google-github-actions/setup-gcloud@v1'

      # --- ¡NUEVOS PASOS COMIENZAN AQUÍ! ---

      - name: Conectar a Cloud SQL (Auth Proxy)
        uses: google-github-actions/connect-gcloud-sql@v1
        with:
          # Este comando inicia el proxy en segundo plano.
          instance_connection_name: ${{ env.DB_INSTANCE_CONNECTION_NAME }}

      - name: Ejecutar migraciones de Prisma
        env:
          # El proxy hace que la DB esté disponible en localhost:5432 para el runner de GitHub
          # Por eso, la URL de conexión aquí es diferente a la de Cloud Run.
          DATABASE_URL: "postgresql://${{ env.DB_USER }}:${{ secrets.DB_PASSWORD }}@127.0.0.1:5432/${{ env.DB_NAME }}"
        run: npx prisma migrate deploy

      # --- NUEVOS PASOS TERMINAN AQUÍ ---

      - name: Configurar Docker para Artifact Registry
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Construir y subir la imagen de Docker
        run: |-
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Desplegar en Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.GAR_LOCATION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          env_vars: |-
            # Esta URL usa el socket interno de Cloud Run, es diferente a la del paso de migración.
            DATABASE_URL=postgresql://${{ env.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost/${{ env.DB_NAME }}?host=/cloudsql/${{ env.DB_INSTANCE_CONNECTION_NAME }}